export const DEFAULT_ZONES: Array<{ id: string; name: string; order: number; active: boolean }> = [
  { id: "chapala", name: "Chapala", order: 1, active: true },
  { id: "cihuatlan", name: "Cihuatlán", order: 2, active: true },
  { id: "cuauhtemoc", name: "Cuauhtémoc", order: 3, active: true },
  { id: "juanacatlan", name: "Juanacatlán", order: 4, active: true },
  { id: "san-isidro", name: "San Isidro Mazatepec", order: 5, active: true },
  { id: "sayula", name: "Sayula", order: 6, active: true },
  { id: "tepa", name: "Tepatitlán", order: 7, active: true },
  { id: "tepic", name: "Tepic", order: 8, active: true },
  { id: "tequila", name: "Tequila", order: 9, active: true },
  { id: "tesistan", name: "Tesistán", order: 10, active: true },
  { id: "tlajomulco", name: "Tlajomulco", order: 11, active: true },
  { id: "tlaquepaque", name: "Tlaquepaque", order: 12, active: true },
  { id: "tonala", name: "Tonalá", order: 13, active: true },
  { id: "zapopan", name: "Zapopan", order: 14, active: true },
  { id: "zmg", name: "ZMG", order: 15, active: true },
  { id: "tequila", name: "Tequila", order: 16, active: true },
];
